# Generated by Django 5.1.7 on 2025-04-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorados", "0004_rename_disponibilidade_disponibilidadehorarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorados",
            name="token",
            field=models.CharField(default=12, max_length=16),
            preserve_default=False,
        ),
    ]
